name: Backend CI
on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      NEO4J_URI:  ${{ secrets.NEO4J_URI }}
      NEO4J_USER: ${{ secrets.NEO4J_USER }}
      NEO4J_PASS: ${{ secrets.NEO4J_PASS }}
    steps:
      - uses: actions/checkout@v3

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Test
        run: ./mvnw clean verify
