name: CI
on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      # these must match both your GitHub‑Secrets *and* your Spring Boot config
      NEO4J_URI:    ${{ secrets.NEO4J_URI }}
      NEO4J_USER:   ${{ secrets.NEO4J_USER }}
      NEO4J_PASS:   ${{ secrets.NEO4J_PASS }}
    steps:
      - uses: actions/checkout@v3

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build & Test Backend
        run: ./mvnw clean verify

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install & Test
        working-directory: frontend
        run: |
          npm ci
          npm test
