name: Backend CI
on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest

    # Correctly indented env block
    env:
      AURA_URI:      ${{ secrets.NEO4J_URI }}
      AURA_USER:     ${{ secrets.NEO4J_USER }}
      AURA_PASSWORD: ${{ secrets.NEO4J_PASS }}

    steps:
      - uses: actions/checkout@v3

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build & Test
        run: ./mvnw clean verify
